version: "3"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ='America/New_York'
    volumes:
      - ./config:/config
      - HOST PATH FOR TEMP DOWNLOADS:/downloads
      - HOST PATH FOR FINAL DOWNLOADS:/tv
    network_mode: container:openvpn