version: "3"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - TZ='America/New_York'
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    network_mode: "bridge"