version: "3.5"

services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8088:8080
    network_mode: "bridge"

volumes:
  postgres:
    driver: local
   
