version: "3"

services:
  vpn:
    build: .
    container_name: openvpn
    command: Netherlands.ovpn
    volumes:
      - .:/etc/openvpn
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      
    #TODO, remove network_mode host, must forward ports